film:
  image_width: 2000
  image_height: 2000
  film_size: 16
  bucket_width: 64
  bucket_height: 64
  filter_radius: 2.0
camera:
  position: [0.0,0.0,3.0]
  target: [0.0,0.0,0.0]
  fov: 60.0
sampler:
  max_samples: 1024
  min_samples: 32
  method: sobol
renderer:
  depth_limit: 8
  threads: 10
scene:
  background_color: [0.0,0.0,0.0]