film:
  image_width: 800
  image_height: 800
  film_size: 16
  bucket_width: 64
  bucket_height: 64
camera:
  position: [0.0,-0.1,2.5]
  target: [0.0,-0.1,0.0]
  fov: 60.0
sampler:
  max_samples: 64
  min_samples: 1
  method: sobol
renderer:
  depth_limit: 12
  threads: 7