film:
  image_width: 1000
  image_height: 1000
  bucket_width: 64
  bucket_height: 64
  filter_radius: 1.8
  filter_method: none
#  crop:
#    start: [300,300]
#    end: [400,400]
camera:
  position: [0.0,0.0,3.0]
  target: [0.0,0.0,0.0]
  fov: 60.0
sampler:
  max_samples: 64
  min_samples: 8
  method: sobol
renderer:
  depth_limit: 4
  threads: 10
scene:
  background_color: [1.0,1.0,1.0]