film:
  image_width: 1000
  image_height: 1000
  film_size: 16
  bucket_width: 128
  bucket_height: 128
  filter_radius: 1.5
  filter_method: box
#  crop:
#    start: [900,900]
#    end: [1100,1100]
camera:
  position: [0.0,0.0,3.0]
  target: [0.0,0.0,0.0]
  fov: 60.0
sampler:
  max_samples: 8
  min_samples: 1
  method: sobol
renderer:
  depth_limit: 8
  threads: 1
scene:
  background_color: [0.0,0.0,0.0]