name: Rust

on: [ push ]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: install_dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Download OIDN
        run: |
          mkdir ~/oidn
          cd ~
          wget -q -O oidn.tar.gz https://github.com/OpenImageDenoise/oidn/releases/download/v1.4.3/oidn-1.4.3.x86_64.linux.tar.gz
          tar -xf oidn.tar.gz -C ~/oidn
          echo "OIDN_DIR=~/oidn" >> $GITHUB_ENV
  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Build
        run: |
          echo $OIDN_DIR
          cargo build

  fmt:
    runs-on: ubuntu-latest
    needs: [ dependencies ]
    steps:
      - name: Fmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Clippy
        run: cargo clippy -- -D warnings

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Tests
        run: cargo test --verbose
