name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    components: clippy
                    override: true
            -   name: install_dependencies
                run: |
                    sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
                    sudo apt-get update -y -qq
                    sudo apt-get install libsdl2-dev
#            -   name: Build
#                run: cargo build
            -   name: Fmt
                run: cargo fmt -- --check
            -   name: Clippy
                run: cargo clippy -- -D warnings
            -   name: Run tests
                run: cargo test --verbose
